<ncl id="myNCLDocID" xmlns="http://www.ncl.org.br/NCL3.0/EDTVProfile">
	<head>
		<connectorBase id="connBaseId">
			<importBase alias="conn" documentURI="defaultConnBase.ncl">
			</importBase>
		</connectorBase>
		<regionBase id="regionBase0">
			<region height="100.00%" id="region0" left="0.00%" top="0.00%" width="100.00%" zIndex="1">
			</region>
		</regionBase>
	</head>
	<body id="myBodyID">
		<media id="GYMKHANA" src="media/KEN BLOCK'S GYMKHANA FIVE.mp4">
		</media>
	</body>
</ncl>
